arch/arch/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView
from arch_app.views import CustomLoginView
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
# import debug_toolbar

# urlpatterns = [
#     path('', include('arch_app.urls')),
#     path('admin/', admin.site.urls),
# ]

urlpatterns = i18n_patterns(
    path('accounts/password_reset/', PasswordResetView.as_view(
        html_email_template_name='registration/password_reset_email.html'
    )),
    path('accounts/login/', CustomLoginView.as_view()),  # override login page
    path('accounts/', include('django.contrib.auth.urls')),  # build-in login and logout page
    path('', include('arch_app.urls')),
    path('admin/', admin.site.urls),
    # path('__debug__/', include('debug_toolbar.urls')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arch/arch_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'arch_app'

urlpatterns = [
                  # landing page
                  path('', views.IndexView.as_view(), name='index'),
                  # activation link
                  path('activate/<str:uidb64>/<str:token>/', views.ActivateAccountView.as_view(), name='activate'),
                  path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
                  # archive homepage
                  path("<str:archive_name>/<int:pk>/home/", views.ArchiveDetailView.as_view(),
                       name="archive"),
                  # members page of an archive
                  path("<str:archive_name>/<int:pk>/members/", views.MembersViews.as_view(), name="members"),
                  # create or add member
                  path('add_member/', views.CreateAddMemberView.as_view(), name='add_member'),

                  # membership date
                  path('membership_date/<int:pk>/', views.MembershipDateFormView.as_view(), name='membership_date'),
                  # user profile
                  path("profile/", views.ProfileView.as_view(), name='profile'),

                  # search
                  path("search/", views.SearchView.as_view(), name="search"),

                  # record details
                  path('record/<pk>', views.RecordView.as_view(), name='record'),
                  # delete record
                  path('record/<pk>/delete', views.delete_record, name='delete_record'),
                  # upload record
                  path('<str:archive_name>/<int:archive_id>/upload_record/',
                       views.FileUploadView.as_view(), name='upload_record'),
                  # update record album (change album via drag and drop)
                  path('record_update/', views.RecordUpdateView.as_view(), name='update_record'),
                  # hide comment
                  path('comment/<pk>/hide', views.hide_comment, name='hide_comment'),
                  # create new tag
                  path('record/<pk>/create_tag', views.TagCreateView.as_view(), name='create_tag'),
                  # create new TagBox
                  path('record/<pk>/create_tag_box', views.create_tag_box, name='create_tag_box'),
                  # update tag user on an image
                  path('tag/<pk>', views.UpdateTagView.as_view(), name='tag_user'),
                  # delete tag
                  path('tag/<pk>/delete', views.delete_tag, name='delete_tag'),
                  # pixelate TagBox
                  path('pixelate/<pk>', views.pixelate_image, name='pixelate_image'),
                  # unblur tagbox
                  path('show_tag/<pk>', views.show_tag, name='show_tag'),
                  # create new album
                  path('<str:archive_name>/<int:archive_id>/new_album/', views.AlbumCreateView.as_view(),
                       name='create_album'),
                  # album list
                  path('album_list/<int:archive_pk>', views.AlbumListView.as_view(), name='album_list'),
                  # album
                  path('album/<pk>', views.AlbumView.as_view(), name='album'),
                  # delete album
                  path('album/<pk>/delete', views.delete_album, name='delete_album'),
                  # update album
                  path('album/<pk>/update', views.AlbumUpdateView.as_view(), name='update_album'),

                  # get autocomplete suggestions from database
                  path('autocomplete/', views.autocomplete, name='autocomplete'),
                  # sets the language of the app
                  path('set_language', views.set_language, name='set_language'),
                  # feedback form
                  path('feedback/', views.feedback_view, name='feedback'),
                  # privacy settings
                  path('privacy_settings/', views.PrivacySettingsView.as_view(), name='privacy_settings'),
                  # hide personal data
                  path('hide_personal_data/', views.hide_personal_data, name='hide_personal_data'),
                  # delete account and all data
                  path('delete_account/<str:uidb64>/<str:token>', views.DeleteAccountView.as_view(),
                       name='delete_account'),

                  # dashboard for usage statistics
                  path('dashboard/', views.DashboardView.as_view(), name='dashboard'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arch/arch_app/views.py
from urllib.parse import urlencode
from django.contrib.auth import logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView
from django.db.models.functions import Trunc
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Case, When, Q, Count
from django.db.utils import IntegrityError, DataError
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import generic, View
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import translation
from django.utils.translation import gettext as _
from django.views.generic.edit import FormMixin, FormView
from django.utils.encoding import force_bytes, force_str
from django.http import JsonResponse
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import PasswordResetTokenGenerator, default_token_generator
from itertools import chain

from .forms import *
from .utils import send_email
from PIL import Image
# import modules
from .modules.metadata_extraction.file_processing import extract_metadata, determine_type
from .modules.search.helpers import SearchMixin
from .modules.computer_vision.blur_image import blur_image, unblur_image
from guardian.shortcuts import assign_perm, get_objects_for_user, remove_perm
from datetime import datetime
import logging
from django.conf import settings

from django_q.tasks import async_task
from .tasks import create_tagboxes_and_save, generate_preview_and_save, generate_image_embedding_and_save


console_logger = logging.getLogger('ARCH_console_logger')
file_logger = logging.getLogger('ARCH_file_logger')
PAGINATE_BY = 20


class TokenGenerator(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (
                str(user.pk) + str(timestamp) +
                str(user.is_active)
        )


account_activation_token = TokenGenerator()


class IndexView(generic.TemplateView):
    template_name = 'arch_app/home.html'


class CustomLoginView(LoginView):
    """
    Login view
    handles data restoration for hidden users (sets visible to True and shows comments, tags, blurred images)
    tracks the login of the user.
    """

    def form_valid(self, form):
        user = form.get_user()

        if not user.visible:
            # if user is hidden, restore hidden data
            user.visible = True
            user.save()
            for comment in Comment.objects.filter(user=user):
                if comment.visible == 'hidden_by_user':
                    comment.visible = 'visible'
                    comment.save()
            for tagbox in TagBox.objects.filter(user=user):
                if tagbox.visible == 'hidden_by_user':
                    unblur_image(
                        image_path=tagbox.record.preview_file.path,
                        original_file_path=tagbox.record.media_file.path,
                        coordinates=(tagbox.x1, tagbox.y1, tagbox.x2, tagbox.y2))
            for tag in Tag.objects.filter(user=user):
                if tag.visible == 'hidden_by_user':
                    tag.visible = 'visible'
                    tag.save()
            messages.success(self.request, _('Your data was successfully restored and made visible again.'))

        Tracker.objects.create_from_request(request=self.request, content_object=user, user=user)
        return super().form_valid(form)


class ChangePasswordView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    """
    View for changing the password of a user.
    """
    template_name = './arch_app/forms/change_password.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('login')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        # send email to user notifying them that their password has been changed
        user = self.request.user
        email_status = send_email(user.email,
                                  subject='Password Changed',
                                  html_message=render_to_string('arch_app/emails/password_changed_email.html',
                                                                {'user': user,
                                                                 'hostname': self.request.META['HTTP_HOST']}),
                                  )
        if email_status:
            messages.success(self.request, _('Your password has been successfully changed.'))
        else:
            messages.error(self.request,
                           _('An error occurred while sending the email. Please Contact the Administrator.'))

        return super().form_valid(form)


class ActivateAccountView(View):
    """
    View for activating a user account.
    checks if the activation link is valid and activates the user account.
    """

    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            # send email to user notifying them that their account has been activated
            email_status = send_email(user.email,
                                      subject='Welcome to ARCH!',
                                      html_message=render_to_string('registration/welcome_email.html',
                                                                    {'user': user}
                                                                    ),
                                      )
            if email_status:
                messages.success(request, _('Your account has been activated! You can now log in.'))
            else:
                messages.error(request,
                               _('An error occurred while sending the email. Please Contact the Administrator.'))
            return redirect('login')

        else:
            return HttpResponse('Activation link is invalid!')


class CreateAddMemberView(LoginRequiredMixin, generic.TemplateView):
    """
    View for creating a new user and/or adding a user to an archive from the members page
    """
    template_name = 'arch_app/forms/create_add_member_form.html'

    @staticmethod
    def generate_html_message(user, password, request):
        """
        Generate the HTML message for the activation email.
        Creates a token for the activation link and builds the activation URL.

        :param user: the user object
        :param password: the password of the user
        :param request: the request object
        :return: the HTML message
        """
        token = account_activation_token.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        domain = get_current_site(request).domain
        activation_url = reverse('arch_app:activate', kwargs={'uidb64': uid, 'token': token})
        activation_link = f'http://{domain}{activation_url}'  # must be http

        html_message = render_to_string('registration/activation_email.html', {
            'user': user,
            'activation_link': activation_link,
            'password': password,

        })
        return html_message

    def post(self, request, *args, **kwargs):
        """
        Post method for creating a new user or adding an existing user to an archive.
        checks if the user has permission to add members to the archive and handles the form submission.
        """

        if not request.user.has_perm('is_moderator', Archive.objects.get(id=request.POST['archive'])):
            messages.error(request, _('You do not have permission to add members to this archive.'))
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        add_member_form = AddMemberForm(request.POST)
        if add_member_form.is_valid():
            cleaned_data = add_member_form.cleaned_data

            if User.objects.filter(username=cleaned_data['username'], email=cleaned_data['email']).exists():
                # create membership for existing user
                user = User.objects.get(username=cleaned_data['username'], email=cleaned_data['email'])
                archive = Archive.objects.get(id=request.POST['archive'])
                # check if membership with this role already exists
                membership, created = Membership.objects.get_or_create(user=user,
                                                                       archive=archive,
                                                                       role=cleaned_data['role'])
                if created:
                    messages.success(request, _('An existing user with the given username and email was added.'))
                else:
                    messages.warning(request,
                                     _('An existing user with the given username and email is already a member of this group.'))

            else:
                # check if username or email are already taken
                if User.objects.filter(username=cleaned_data['username']).exists():
                    messages.warning(request, _('Username is already taken.'))
                    return redirect(request.META.get('HTTP_REFERER'))
                if User.objects.filter(email=cleaned_data['email']).exists():
                    messages.warning(request, _('Email is already taken.'))

arch/arch_app/templates/arch_app/partials/album_item.html
{% load arch_tags %}
{% load i18n %}
{% load static %}


{#<div class="card border-dark mb-3">#}
{#    <div class="card-header">#}
{#        {{ album.title }}#}
{#    </div>#}
{#    <div class="card-body text-dark">#}
{##}
{#        <p class="card-text">#}
{##}
{#            {% if album.get_start_date %}#}
{#                ({{ album.get_start_date }} {% if album.get_end_date %}- {{ album.get_end_date }} {% endif %})#}
{#            {% endif %}#}
{##}
{#        </p>#}
{##}
{##}
{#                <a href="{% url 'arch_app:album' album.id %}">#}
{#                    <i class="bi bi-folder" style="font-size: 5rem;"></i>#}
{#                </a>#}
{##}
{#    </div>#}


<div class="p-2 m-2" style="border: 2px solid lightgray; border-radius: 10px;">

    <div class="row m-0 px-1 justify-content-center">
        <div class="col text-center">
            <h6 class="text-truncate ">
                {{ album.title }}
            </h6>
        </div>
    </div>

    <div class="row m-0 p-0 justify-content-end">
        <div class="col p-0">
            <div class="text-muted text-truncate text-center" style="font-size: xx-small">
                {% with start_date=album.get_start_date %}
                    {% with end_date=album.get_end_date %}
                        {% if start_date %}
                            <div class="col-auto" title="{% trans 'Time span covered by this Album' %}">
                                ( {{ start_date }}
                                {% if end_date and start_date != end_date %}
                                    - {{ end_date }}
                                {% endif %}
                                )
                            </div>
                        {% endif %}
                    {% endwith %}
                {% endwith %}
            </div>
        </div>
    </div>

    <div class="row p-1 justify-content-center">
        <div class="col text-center">
            <a href="{% url 'arch_app:album' album.id %}">
                <i class="bi bi-folder" style="font-size: 5rem;"></i>
            </a>
        </div>
    </div>

</div>

arch/arch_app/templates/arch_app/partials/archive_home.html
{% extends "arch_app/archive.html" %}
{% load i18n %}
{% load static %}
{% load arch_tags %}


{% block archive_settings %}

    {% get_archive_form archive as archive_form %}
    {% include "../forms/archive_form.html" %}

{% endblock %}

arch/arch_app/templates/arch_app/partials/gallery.html
{% load i18n %}
{% load static %}


<div class="row justify-content-around">

    {% for record in record_list %}

        {% if forloop.counter0|divisibleby:4 %}
            {% if forloop.counter0 == 0 %}
                <div class="row">
            {% else %}
                </div>
                <div class="row">
            {% endif %}
        {% endif %}

        <div class="col-md-3 py-sm-5 py-md-2 m-0 p-2">

            {% include "./record/record_item.html" %}

        </div>

    {% endfor %}
    </div>
</div>

arch/arch_app/templates/arch_app/partials/language_button.html
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

    <form action="{% url 'arch_app:set_language' %}" method="post">
        {% csrf_token %}

        <select name="language" id="language" onchange="this.form.submit()">
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}
                        selected="selected" {% endif %} >
                    {{ language.name_local }}
                </option>
            {% endfor %}
        </select>
        <input type="hidden" id="origin_url" name="origin_url" value={{ request.path }}>

        <img class="img-fluid"
             src="{% static 'arch_app/img/flags/' %}{{ LANGUAGE_CODE }}.svg"
             alt="flag-{{ LANGUAGE_CODE }}"
             style="width:2em; height:2em;"
        />

    </form>

arch/arch_app/templates/arch_app/partials/navbar.html
{% load i18n %}
{% load static %}
{% load arch_tags %}


{% block navbar %}

    <nav class="navbar rounded my-2 mx-1"
         id="arch-navbar">

        {#ARCH brand#}
        <div class="col-xs-auto col-sm-6 col-md-2 order-md-first">

            <a class="" href="{% url 'arch_app:index' %}">

                <h1 class="text-dark font-weight-bold">ARCH</h1>

                {#                <h3>#}
                {#                    <b class="text-primary"><i>Memory</i></b><b class="text-secondary">Net</b>#}
                {#                </h3>#}

                {#                <div class="logo">#}
                {#                    <h1 class="text-primary">#}
                {#                        DIVE#}
                {#                    </h1>#}
                {#                    <h1 class="text-dark">#}
                {#                        DIVE#}
                {#                    </h1>#}
                {#                </div>#}

                {#                <!-- logo for large screen -->#}
                {#                <i class="d-none d-sm-inline-block">#}
                {#                    <b>E<i class="fs-2 text-primary">X</i>OGR<i class="bi bi-triangle fs-3 text-secondary"></i>M</b></i>#}
                {#                <!-- logo for small screen -->#}
                {#                <i class="d-sm-none d-inline-block">#}
                {#                    <b class="fs-2 pl-1 text-primary" style="position: absolute"><i>X</i></b>#}
                {#                    <i class="bi bi-triangle fs-3 text-secondary"></i>#}
                {#                </i>#}

                {#                 include Logo #}
                {#                 <i style="font-size: medium">#}
                {#                     <img style="height: 80px;"#}
                {#                          src="{% static 'arch_app/img/drawing.svg' %}"#}
                {#                          alt="App Logo"#}
                {#                          loading="lazy">#}
                {#                 </i>#}

            </a>
        </div>

        {#Contains navigation to archive, upload button and conf button#}
        <div class="col-xs-auto col-sm-6 col-md-3 order-md-last">

            <div class="row justify-content-end">

                {# navigation to archives #}
                <div class="col-auto p-1">
                    {% if  user.is_authenticated %}
                        {% get_archives_for_user user as archives %}
                        {% if archives %}
                            <div class="d-flex mx-1" style="height: 100%;">

                                {% if archives|length < 2 %}
                                    <a class="btn btn-dark d-flex my-auto"
                                       href="{% url 'arch_app:archive' archives.0.name|slugify archives.0.id %}">
                                        <i class="bi bi-house-door"></i> {{ archives.0.name }}
                                    </a>

                                {% else %}
                                    <div class="dropdown my-auto">
                                        <a class="btn btn-dark" id="archivesDropdown"
                                           role="button" href="#"
                                           data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="bi bi-house-door"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="archivesDropdown">
                                            {% for archive in archives %}
                                                <a class="dropdown-item text-primary"
                                                   href="{% url 'arch_app:archive' archive.name|slugify archive.id %}">
                                                    {{ archive.name }}
                                                </a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endif %}
                </div>

                {# upload button #}
                <div class="col-auto p-1">
                    {% include "../partials/upload_button.html" %}
                </div>
                {#Conf button#}
                <div class="col-auto p-1">

                    <div class="dropdown ">
                        <div id="navbarDropdown" role="button"
                             data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                            {% if user.is_authenticated and user.profile_picture %}
                                <img class="rounded-circle"
                                     style="height: 3em; width: 3em; object-fit: cover; border: 1px white solid"
                                     src="{{ user.profile_picture.url }}"
                                     alt="User Profile"
                                     loading="lazy">
                            {% else %}
                                <i class="bi bi-person-circle fs-1 text-dark"></i>
                            {% endif %}

                        </div>

                        <div class="dropdown-menu dropdown-menu-end"
                             aria-labelledby="navbarDropdown"
                             style="min-width: 14rem">

                            {% if  user.is_authenticated %}
                                <h4 class="dropdown-item text-primary">{{ user.username }}</h4>
                                <hr class="dropdown-divider">
                            {% endif %}

                            <div class="dropdown-item">
                                {% include "./language_button.html" %}
                            </div>

                            {% if user.is_authenticated %}

                                <a class="dropdown-item text-primary" href="{% url 'arch_app:profile' %}">
                                    {% trans "Settings" %}
                                </a>
                                {% if user.is_superuser %}
                                    <a class="dropdown-item text-primary" href="/admin">{% trans "Administration" %}</a>
                                    <a class="dropdown-item text-primary" href="{% url 'arch_app:dashboard' %}">
                                        {% trans "Dashboard" %}
                                    </a>
                                {% endif %}
                                <a class="dropdown-item text-primary" href="{% url 'logout' %}?next={{ request.path }}">
                                    {% trans "Log out" %}
                                </a>

                            {% else %}
                                <a class="dropdown-item text-primary" href="{% url 'login' %}?next={{ request.path }}">
                                    {% trans "Login" %}
                                </a>
                            {% endif %}

                        </div>
                    </div>

                </div>

            </div>

        </div>  <!-- col -->

        <div class="col-xs-auto col-sm-12 col-md-6 justify-content-center d-flex mx-sm-1 mx-md-1 mx-lg-0">
            {% include "./searchbar.html" %}
        </div>

    </nav>  <!-- navbar -->

    {% include "./search_filters.html" %}


{% endblock %}

arch/arch_app/templates/arch_app/partials/spinner.html
{% load static %}

<div class="d-flex justify-content-center">
    <div class="spinner-border text-success d-none" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

{#<script src="{% static 'arch_app/js/spinner.js' %}"></script>#}

arch/arch_app/templates/arch_app/partials/tagbox.html
{% load i18n %}
{% load static %}
{% load arch_tags %}
{% load mathfilters %}
{% load guardian_tags %}


{# get user permissions #}
{% get_obj_perms user for tagbox.record.album.archive as "archive_perms" %}


<div class="tag-box m-0" id="tag-{{ tagbox.id }}"
        {# calculate the position of the box based on the size of the image #}
     style="top: {{ tagbox.y1|div:tagbox.height|mul:100|stringformat:".2f" }}%;
             left: {{ tagbox.x1|div:tagbox.width|mul:100|stringformat:".2f" }}%;
             width: {{ tagbox.x2|sub:tagbox.x1|div:tagbox.width|mul:100|stringformat:".2f" }}%;
             height: {{ tagbox.y2|sub:tagbox.y1|div:tagbox.height|mul:100|stringformat:".2f" }}%;
             position: absolute;
             {% if tagbox.visible == "visible" %}
                 border: solid thin white;
             {% endif %}
             "
        {% if tagbox.visible == 'visible' %}
     title="{{ tagbox.user.username }}"
        {% endif %}>

    {# TagBox Form #}
    {% if "is_moderator" in archive_perms %}
        {% if tagbox.visible == 'visible' %}
            <div class="dropdown dropright">
                <a class="toggle" href="#" id="TagUserDropdown-{{ tagbox.id }}" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-three-dots-vertical text-white"
                       style="float: right">
                    </i>
                </a>

                <div class="dropdown-menu" id="tag-dropdown-menu-{{ tagbox.id }}"
                     aria-labelledby="TagUserDropdown-{{ tagbox.id }}">
                    <div class="p-1">
                        <div class="dropdown-item">
                            <a href="{% url 'arch_app:delete_tag' tagbox.pk %}"
                               class="btn btn-sm btn-secondary mx-1" role="button"
                               style="float: right"
                               title="{% trans "Delete this Tag" %}">
                                <i class="bi bi-trash text-danger"></i>
                            </a>
                            <a class="btn btn-sm btn-primary mx-1" role="button"
                               title="{% trans "pixelate image" %}"
                               style="float: right"
                               href="{% url 'arch_app:pixelate_image' tagbox.pk %}">
                                <i class="bi bi-eye"></i>
                            </a>
                        </div>
                        <div class="dropdown-item">
                            {% with tag=tagbox %}
                                {% get_tag_form tag as tag_form %}
                                {% include "../forms/tag_form.html" %}
                            {% endwith %}
                        </div>

                    </div>
                </div>

            </div>
        {% endif %}
        {% if tagbox.visible == 'hidden_by_mod' %}
            <a href="{% url "arch_app:show_tag" tagbox.id %}"
               title="{% trans "undo pixelation" %}">
                <i class="bi bi-eye-slash fs-1 text-white" style="float: right"></i>
            </a>
        {% endif %}
    {% endif %}
</div>