arch/arch/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView
from arch_app.views import CustomLoginView
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
# import debug_toolbar

# urlpatterns = [
#     path('', include('arch_app.urls')),
#     path('admin/', admin.site.urls),
# ]

urlpatterns = i18n_patterns(
    path('accounts/password_reset/', PasswordResetView.as_view(
        html_email_template_name='registration/password_reset_email.html'
    )),
    path('accounts/login/', CustomLoginView.as_view()),  # override login page
    path('accounts/', include('django.contrib.auth.urls')),  # build-in login and logout page
    path('', include('arch_app.urls')),
    path('admin/', admin.site.urls),
    # path('__debug__/', include('debug_toolbar.urls')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arch/arch_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'arch_app'

urlpatterns = [
                  # landing page
                  path('', views.IndexView.as_view(), name='index'),
                  # activation link
                  path('activate/<str:uidb64>/<str:token>/', views.ActivateAccountView.as_view(), name='activate'),
                  path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
                  # archive homepage
                  path("<str:archive_name>/<int:pk>/home/", views.ArchiveDetailView.as_view(),
                       name="archive"),
                  # members page of an archive
                  path("<str:archive_name>/<int:pk>/members/", views.MembersViews.as_view(), name="members"),
                  # create or add member
                  path('add_member/', views.CreateAddMemberView.as_view(), name='add_member'),

                  # membership date
                  path('membership_date/<int:pk>/', views.MembershipDateFormView.as_view(), name='membership_date'),
                  # user profile
                  path("profile/", views.ProfileView.as_view(), name='profile'),

                  # search
                  path("search/", views.SearchView.as_view(), name="search"),

                  # record details
                  path('record/<pk>', views.RecordView.as_view(), name='record'),
                  # delete record
                  path('record/<pk>/delete', views.delete_record, name='delete_record'),
                  # upload record
                  path('<str:archive_name>/<int:archive_id>/upload_record/',
                       views.FileUploadView.as_view(), name='upload_record'),
                  # update record album (change album via drag and drop)
                  path('record_update/', views.RecordUpdateView.as_view(), name='update_record'),
                  # hide comment
                  path('comment/<pk>/hide', views.hide_comment, name='hide_comment'),
                  # create new tag
                  path('record/<pk>/create_tag', views.TagCreateView.as_view(), name='create_tag'),
                  # create new TagBox
                  path('record/<pk>/create_tag_box', views.create_tag_box, name='create_tag_box'),
                  # update tag user on an image
                  path('tag/<pk>', views.UpdateTagView.as_view(), name='tag_user'),
                  # delete tag
                  path('tag/<pk>/delete', views.delete_tag, name='delete_tag'),
                  # pixelate TagBox
                  path('pixelate/<pk>', views.pixelate_image, name='pixelate_image'),
                  # unblur tagbox
                  path('show_tag/<pk>', views.show_tag, name='show_tag'),
                  # create new album
                  path('<str:archive_name>/<int:archive_id>/new_album/', views.AlbumCreateView.as_view(),
                       name='create_album'),
                  # album list
                  path('album_list/<int:archive_pk>', views.AlbumListView.as_view(), name='album_list'),
                  # album
                  path('album/<pk>', views.AlbumView.as_view(), name='album'),
                  # delete album
                  path('album/<pk>/delete', views.delete_album, name='delete_album'),
                  # update album
                  path('album/<pk>/update', views.AlbumUpdateView.as_view(), name='update_album'),

                  # get autocomplete suggestions from database
                  path('autocomplete/', views.autocomplete, name='autocomplete'),
                  # sets the language of the app
                  path('set_language', views.set_language, name='set_language'),
                  # feedback form
                  path('feedback/', views.feedback_view, name='feedback'),
                  # privacy settings
                  path('privacy_settings/', views.PrivacySettingsView.as_view(), name='privacy_settings'),
                  # hide personal data
                  path('hide_personal_data/', views.hide_personal_data, name='hide_personal_data'),
                  # delete account and all data
                  path('delete_account/<str:uidb64>/<str:token>', views.DeleteAccountView.as_view(),
                       name='delete_account'),

                  # dashboard for usage statistics
                  path('dashboard/', views.DashboardView.as_view(), name='dashboard'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arch/arch_app/views.py
from urllib.parse import urlencode
from django.contrib.auth import logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView
from django.db.models.functions import Trunc
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Case, When, Q, Count
from django.db.utils import IntegrityError, DataError
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import generic, View
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import translation
from django.utils.translation import gettext as _
from django.views.generic.edit import FormMixin, FormView
from django.utils.encoding import force_bytes, force_str
from django.http import JsonResponse
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import PasswordResetTokenGenerator, default_token_generator
from itertools import chain

from .forms import *
from .utils import send_email
from PIL import Image
# import modules
from .modules.metadata_extraction.file_processing import extract_metadata, determine_type
from .modules.search.helpers import SearchMixin
from .modules.computer_vision.blur_image import blur_image, unblur_image
from guardian.shortcuts import assign_perm, get_objects_for_user, remove_perm
from datetime import datetime
import logging
from django.conf import settings

from django_q.tasks import async_task
from .tasks import create_tagboxes_and_save, generate_preview_and_save, generate_image_embedding_and_save


console_logger = logging.getLogger('ARCH_console_logger')
file_logger = logging.getLogger('ARCH_file_logger')
PAGINATE_BY = 20


class TokenGenerator(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (
                str(user.pk) + str(timestamp) +
                str(user.is_active)
        )


account_activation_token = TokenGenerator()


class IndexView(generic.TemplateView):
    template_name = 'arch_app/home.html'


class CustomLoginView(LoginView):
    """
    Login view
    handles data restoration for hidden users (sets visible to True and shows comments, tags, blurred images)
    tracks the login of the user.
    """

    def form_valid(self, form):
        user = form.get_user()

        if not user.visible:
            # if user is hidden, restore hidden data
            user.visible = True
            user.save()
            for comment in Comment.objects.filter(user=user):
                if comment.visible == 'hidden_by_user':
                    comment.visible = 'visible'
                    comment.save()
            for tagbox in TagBox.objects.filter(user=user):
                if tagbox.visible == 'hidden_by_user':
                    unblur_image(
                        image_path=tagbox.record.preview_file.path,
                        original_file_path=tagbox.record.media_file.path,
                        coordinates=(tagbox.x1, tagbox.y1, tagbox.x2, tagbox.y2))
            for tag in Tag.objects.filter(user=user):
                if tag.visible == 'hidden_by_user':
                    tag.visible = 'visible'
                    tag.save()
            messages.success(self.request, _('Your data was successfully restored and made visible again.'))

        Tracker.objects.create_from_request(request=self.request, content_object=user, user=user)
        return super().form_valid(form)


class ChangePasswordView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    """
    View for changing the password of a user.
    """
    template_name = './arch_app/forms/change_password.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('login')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        # send email to user notifying them that their password has been changed
        user = self.request.user
        email_status = send_email(user.email,
                                  subject='Password Changed',
                                  html_message=render_to_string('arch_app/emails/password_changed_email.html',
                                                                {'user': user,
                                                                 'hostname': self.request.META['HTTP_HOST']}),
                                  )
        if email_status:
            messages.success(self.request, _('Your password has been successfully changed.'))
        else:
            messages.error(self.request,
                           _('An error occurred while sending the email. Please Contact the Administrator.'))

        return super().form_valid(form)


class ActivateAccountView(View):
    """
    View for activating a user account.
    checks if the activation link is valid and activates the user account.
    """

    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            # send email to user notifying them that their account has been activated
            email_status = send_email(user.email,
                                      subject='Welcome to ARCH!',
                                      html_message=render_to_string('registration/welcome_email.html',
                                                                    {'user': user}
                                                                    ),
                                      )
            if email_status:
                messages.success(request, _('Your account has been activated! You can now log in.'))
            else:
                messages.error(request,
                               _('An error occurred while sending the email. Please Contact the Administrator.'))
            return redirect('login')

        else:
            return HttpResponse('Activation link is invalid!')


class CreateAddMemberView(LoginRequiredMixin, generic.TemplateView):
    """
    View for creating a new user and/or adding a user to an archive from the members page
    """
    template_name = 'arch_app/forms/create_add_member_form.html'

    @staticmethod
    def generate_html_message(user, password, request):
        """
        Generate the HTML message for the activation email.
        Creates a token for the activation link and builds the activation URL.

        :param user: the user object
        :param password: the password of the user
        :param request: the request object
        :return: the HTML message
        """
        token = account_activation_token.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        domain = get_current_site(request).domain
        activation_url = reverse('arch_app:activate', kwargs={'uidb64': uid, 'token': token})
        activation_link = f'http://{domain}{activation_url}'  # must be http

        html_message = render_to_string('registration/activation_email.html', {
            'user': user,
            'activation_link': activation_link,
            'password': password,

        })
        return html_message

    def post(self, request, *args, **kwargs):
        """
        Post method for creating a new user or adding an existing user to an archive.
        checks if the user has permission to add members to the archive and handles the form submission.
        """

        if not request.user.has_perm('is_moderator', Archive.objects.get(id=request.POST['archive'])):
            messages.error(request, _('You do not have permission to add members to this archive.'))
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        add_member_form = AddMemberForm(request.POST)
        if add_member_form.is_valid():
            cleaned_data = add_member_form.cleaned_data

            if User.objects.filter(username=cleaned_data['username'], email=cleaned_data['email']).exists():
                # create membership for existing user
                user = User.objects.get(username=cleaned_data['username'], email=cleaned_data['email'])
                archive = Archive.objects.get(id=request.POST['archive'])
                # check if membership with this role already exists
                membership, created = Membership.objects.get_or_create(user=user,
                                                                       archive=archive,
                                                                       role=cleaned_data['role'])
                if created:
                    messages.success(request, _('An existing user with the given username and email was added.'))
                else:
                    messages.warning(request,
                                     _('An existing user with the given username and email is already a member of this group.'))

            else:
                # check if username or email are already taken
                if User.objects.filter(username=cleaned_data['username']).exists():
                    messages.warning(request, _('Username is already taken.'))
                    return redirect(request.META.get('HTTP_REFERER'))
                if User.objects.filter(email=cleaned_data['email']).exists():
                    messages.warning(request, _('Email is already taken.'))

arch/arch_app/templates/arch_app/forms/album_members_form.html
<form method="POST"
       action="{% url 'arch_app:update_album' album.id %}?type_of_form=update_album_members_form"
      enctype="multipart/form-data"
id="update-album-members-form">
    {% csrf_token %}

    {{ album_members_form.users }}


</form>

arch/arch_app/templates/arch_app/forms/change_password.html
{% extends "arch_app/account_settings.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block account_settings %}
    <form action="{% url 'arch_app:change_password' %}" method="post" class="py-3">

        {% csrf_token %}
        {{ form|crispy }}


        <div class="text-right mt-3">
            <button type="submit" class="btn btn-primary" title="Change Password">{% trans "Change Password" %}</button>&nbsp;
            <a href="{% url 'arch_app:profile' %}" class="btn btn-outline-danger">{% trans "Cancel" %}</a>
        </div>

    </form>




{% endblock %}

arch/arch_app/templates/arch_app/forms/create_add_member_form.html
{% load i18n %}


<form action="{% url 'arch_app:add_member' %}"
      method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{  form.as_p  }}
    <input type="hidden" name="archive" value="{{ archive.id }}">

    <button type="submit" value="Submit" class="btn btn-primary">{% trans "Submit" %}</button>

</form>

arch/arch_app/templates/arch_app/forms/profile_form.html
{% extends "arch_app/account_settings.html" %}
{% load i18n %}
{% load static %}


{% block account_settings %}



    <div class="tab-pane fade active show">


        <div class="card-body media align-items-center">


            {% if user.profile_picture %}
                <img class="img-thumbnail rounded-circle"
                     style="width: 10em; height: 10em; object-fit: cover;"
                     src="{{ user.profile_picture.url }}"
                     alt="{% trans "Profile picture" %}"
                     loading="lazy">
            {% else %}
                <img class="img-thumbnail rounded-circle"
                     style="width: 10em; height: 10em;"
                     src="{% static 'arch_app/icons/person-circle.svg' %}"
                     loading="lazy">
            {% endif %}


            <div class="media-body ml-4">

                <h2>{{ user.username }}</h2>

                <div class="d-md-flex">

                    <div>

                        <form method="post"
                              action="{% url 'arch_app:profile' %}"
                              enctype="multipart/form-data"
                              class="form-horizontal"
                              id="profile-form-picture">
                            {% csrf_token %}

                            <label class="btn btn-outline-primary">

                                {% if user.profile_picture %}
                                    {% trans "Change Photo" %}
                                {% else %}
                                    {% trans "Upload Photo" %}
                                {% endif %}
                                {{ profile_picture_form.profile_picture.errors }}
                                {{ profile_picture_form.profile_picture }}

                            </label> &nbsp;
                            <input type="hidden" name="action" value="profilePicture">
                        </form>

                    </div>
                    {% if user.profile_picture %}
                        <div>
                            <form
                                    method="post"
                                    action="{% url 'arch_app:profile' %}"
                            >
                                {% csrf_token %}
                                <input type="hidden" name="action" value="Delete">
                                <button type="submit" class="btn btn-warning">{% trans 'Delete' %}</button>
                            </form>

                        </div>

                    {% endif %}

                </div>


            </div>
        </div>


        <hr class="border-light m-0">


        <form method="post"
              action="{% url 'arch_app:profile' %}"
              enctype="multipart/form-data"
              class="form-horizontal"
              id="profile-form-id">
            {% csrf_token %}
            <div class="card-body">


                <div class="form-group">
                    {{ profile_form.bio.errors }}
                    {{ profile_form.bio }}
                </div>


                <div class="form-group">
                    <label class="form-label">{% trans "Username" %}</label>
                    {{ profile_form.username }}
                </div>


                <div class="form-group">
                    <label class="form-label">{% trans "First Name" %}</label>
                    {{ profile_form.first_name.errors }}
                    {{ profile_form.first_name }}

                </div>

                <div class="form-group">
                    <label class="form-label">{% trans "Last Name" %}</label>
                    {{ profile_form.last_name.errors }}
                    {{ profile_form.last_name }}

                </div>

                <div class="form-group">
                    <label class="form-label">E-mail</label>
                    <input readonly type="text" class="form-control mb-1" value= {{ user.email }}>
                </div>


                <div class="form-group">
                    <label class="form-label">{% trans "Date of Birth" %}</label>
                    {{ profile_form.birth_date.errors }}
                    {{ profile_form.birth_date }}
                </div>

            </div>


            <div class="text-right mt-3 pb-3">
                <button type="submit" form="profile-form-id" class="btn btn-primary">
                    {% trans "Save" %}
                </button>&nbsp;
                <a href="{% url 'arch_app:index' %}" class="btn btn-outline-danger">
                    {% trans "Cancel" %}
                </a>
            </div>

            <input type="hidden" name="action" value="save">

        </form>
    </div>

    <script>
        document.getElementById("profile-picture-input").addEventListener("change", function () {
            // Automatically submit the form when a file is selected
            document.getElementById("profile-form-picture").submit();
        });
    </script>

{% endblock %}

arch/arch_app/templates/arch_app/forms/record_form.html
{% load i18n %}
{% load arch_tags %}
{% load guardian_tags %}


{% if not record.type == 'Image' %}
    {# form to tag a person, populated from inside the record-form #}
    {% get_tag_form users=record.album.archive.get_members.all as tag_form %}
    <form action="{% url 'arch_app:create_tag' record.pk %}"
          id="create-tag-form"
          method="POST" enctype="multipart/form-data">
        {% csrf_token %}
    </form>
{% endif %}

<form method="post"
      action="{% url 'arch_app:record' record.pk %}?page={{ current_page }}"
      enctype="multipart/form-data"
      class="form-horizontal"
      id="record-form">
    {% csrf_token %}

    {# get permissions #}
    {% get_obj_perms user for record.album.archive as "archive_perms" %}
    {% get_obj_perms user for record as "record_perms" %}

    <div class="row form-group" title={% trans "Title" %}>

        {% if "is_moderator" in archive_perms or "change_record" in record_perms %}
            {{ record_form.title.errors }}
            <div class="col-md-12">
                <h2 class="py-2">{{ record_form.title }}</h2>
            </div>
        {% else %}
            <div class="col-md-12">
                <h2 class="py-2">{{ record.title }}</h2>
            </div>
        {% endif %}
        <div class="col-md-12 small">
            {% trans "created by " %} {{ record.creator.username }}
        </div>
    </div>

    <hr>

    {# people depicted on the record #}
    <div class="row form-group mx-0 py-1" title="{% trans "Who was there?" %}">
        <div class="col-md-2"><i class="bi bi-people"></i></div>
        <div class="col-md-10">
            <div class="row justify-content-start " id="tag-container">
                {% for tag in record.tags.all %}
                    {% if tag.visible == 'visible' %}
                        <div class="col-4">
                            <div class="d-flex">
                                {% if tag.user.profile_picture %}
                                    <i class="bi px-1 tag-profile-photo" style="font-size: 1rem;">
                                        <img class="img-fluid rounded-circle border overflow-hidden"
                                             style="height: 1rem; width: 1rem; object-fit: cover;"
                                             src="{{ tag.user.profile_picture.url }}"
                                             alt="User Profile"
                                             loading="lazy">
                                    </i>
                                {% else %}
                                    <i class="bi bi-person-circle px-1 tag-profile-photo" style="font-size: 1rem;"></i>
                                {% endif %}
                                {# icon to delete tag (usually hidden) #}
                                <i class="bi bi-person-dash text-warning px-1 delete-tag" data-tag-id="{{ tag.id }}"
                                   style="display: none">
                                </i>

                                {% if tag.user.first_name %}
                                    {{ tag.user.first_name }}
                                {% else %}
                                    {{ tag.user.username }}
                                {% endif %}

                            </div>

                        </div>
                    {% endif %}
                {% endfor %}

                {# tag user button #}
                {% if "is_moderator" in archive_perms %}
                    {% if record.type == 'Image' %}
                        <div class="col-4 mx-1">
                            <div class="d-flex">
                                <i id="drawButton" class="bi bi-person-fill-add btn btn-sm px-1 py-0 text-success"
                                   style="font-size: 1rem;">
                                </i>

                                <i id="remove-user-icon"
                                   class="bi bi-person-fill-dash btn btn-sm px-1 py-0 text-warning"
                                   title="{% trans 'Remove user' %}"
                                   style="font-size: 1rem;">
                                </i>


                            </div>
                        </div>


                    {% else %}  <!-- record is not an image -->
                        <div class="col-4 mx-1" id="CreateTagFormContainer">
                            <div class="d-flex">
                                <div class="dropdown">
                                    <i class="bi bi-person-fill-add btn btn-sm px-1 py-0 text-success"
                                       id="CreateTagDropdowm"
                                       data-bs-toggle="dropdown"
                                       aria-expanded="false"
                                       type="button"
                                       style="font-size: 1rem;">
                                    </i>


                                    <i id="remove-user-icon"
                                       class="bi bi-person-fill-dash btn btn-sm px-1 py-0 text-warning"
                                       title="{% trans 'Remove user' %}"
                                       style="font-size: 1rem;">
                                    </i>

                                    <div class="dropdown-menu">
                                        <div class="m-1">
                                            {{ tag_form.user }}
                                        </div>
                                        <button class="btn btn-sm btn-primary m-1"
                                                id="create-tag-form-submit"
                                                type="submit"
                                                form="create-tag-form">
                                            {% trans "Submit" %}
                                        </button>
                                    </div>
                                </div>  <!-- end dropdown -->

                            </div>
                        </div>
                    {% endif %}  <!-- end record is not an image -->


                {% endif %}
            </div>  <!-- end row -->

        </div>  <!-- end col -->
    </div>  <!-- end row -->


    {# metadata #}
    <div class=" row form-group mx-0 py-1" title="{% trans "When was this taken?" %}">
        {{ record_form.date_created.errors }}
        <div class="col-md-2"><i class="bi bi-calendar-event"></i></div>
        <div class="col-md-10">
            {% if "is_moderator" in archive_perms or "change_record" in record_perms %}
                {{ record_form.date_created }}
            {% else %}
                {% if record.date_created %}
                    {{ record.date_created }}
                {% endif %}
            {% endif %}
        </div>
    </div>

    <div class="row form-group mx-0 py-1" title="{% trans "Where was this taken?" %}">
        {{ location_form.name.errors }}
        {{ location_form.state.errors }}
        {{ location_form.country.errors }}
        <div class="col-md-2"><i class="bi bi-geo-alt"></i></div>
        <div class="col-md-10">
            {% if "is_moderator" in archive_perms or "change_record" in record_perms %}
                <div class="py-1">
                    {{ location_form.name }}
                </div>
                <div class="py-1">
                    {{ location_form.state }}
                </div>
                <div class="py-1">
                    {{ location_form.country }}
                </div>
            {% else %}
                {% if record.location %}
                    {% if record.location.name %}
                        <div class="py-1">
                            {{ record.location.name }}
                        </div>
                    {% endif %}
                    {% if record.location.state %}
                        <div class="py-1">
                            {{ record.location.state }}
                        </div>
                    {% endif %}
                    {% if record.location.country %}
                        <div class="py-1">
                            {{ record.location.country }}
                        </div>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>

    <div class="row form-group mx-0 py-1" title="{% trans "Description" %}">
        {{ record_form.user_caption.errors }}
        <div class="col-md-2"><i class="bi bi-card-text"></i></div>
        <div class="col-md-10">
            {% if "is_moderator" in archive_perms or "change_record" in record_perms %}
                {{ record_form.user_caption }}
            {% else %}
                {% if record.user_caption %}
                    {{ record.user_caption }}
                {% endif %}
            {% endif %}
        </div>
    </div>

    {% if "is_moderator" in archive_perms or "change_record" in record_perms %}
        <div class="row mx-0 py-1 justify-content-end">
            <div class="col-md-10">
                <input type="hidden" name="action" value="save">
                <button type="submit" form="record-form" style="width: 100%"
                        class="btn btn-primary btn-sm" title="Save changes">{% trans "Save" %}</button>
            </div>
        </div>
    {% endif %}

</form>