arch/arch/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView
from arch_app.views import CustomLoginView
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
# import debug_toolbar

# urlpatterns = [
#     path('', include('arch_app.urls')),
#     path('admin/', admin.site.urls),
# ]

urlpatterns = i18n_patterns(
    path('accounts/password_reset/', PasswordResetView.as_view(
        html_email_template_name='registration/password_reset_email.html'
    )),
    path('accounts/login/', CustomLoginView.as_view()),  # override login page
    path('accounts/', include('django.contrib.auth.urls')),  # build-in login and logout page
    path('', include('arch_app.urls')),
    path('admin/', admin.site.urls),
    # path('__debug__/', include('debug_toolbar.urls')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arch/arch_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'arch_app'

urlpatterns = [
                  # landing page
                  path('', views.IndexView.as_view(), name='index'),
                  # activation link
                  path('activate/<str:uidb64>/<str:token>/', views.ActivateAccountView.as_view(), name='activate'),
                  path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
                  # archive homepage
                  path("<str:archive_name>/<int:pk>/home/", views.ArchiveDetailView.as_view(),
                       name="archive"),
                  # members page of an archive
                  path("<str:archive_name>/<int:pk>/members/", views.MembersViews.as_view(), name="members"),
                  # create or add member
                  path('add_member/', views.CreateAddMemberView.as_view(), name='add_member'),

                  # membership date
                  path('membership_date/<int:pk>/', views.MembershipDateFormView.as_view(), name='membership_date'),
                  # user profile
                  path("profile/", views.ProfileView.as_view(), name='profile'),

                  # search
                  path("search/", views.SearchView.as_view(), name="search"),

                  # record details
                  path('record/<pk>', views.RecordView.as_view(), name='record'),
                  # delete record
                  path('record/<pk>/delete', views.delete_record, name='delete_record'),
                  # upload record
                  path('<str:archive_name>/<int:archive_id>/upload_record/',
                       views.FileUploadView.as_view(), name='upload_record'),
                  # update record album (change album via drag and drop)
                  path('record_update/', views.RecordUpdateView.as_view(), name='update_record'),
                  # hide comment
                  path('comment/<pk>/hide', views.hide_comment, name='hide_comment'),
                  # create new tag
                  path('record/<pk>/create_tag', views.TagCreateView.as_view(), name='create_tag'),
                  # create new TagBox
                  path('record/<pk>/create_tag_box', views.create_tag_box, name='create_tag_box'),
                  # update tag user on an image
                  path('tag/<pk>', views.UpdateTagView.as_view(), name='tag_user'),
                  # delete tag
                  path('tag/<pk>/delete', views.delete_tag, name='delete_tag'),
                  # pixelate TagBox
                  path('pixelate/<pk>', views.pixelate_image, name='pixelate_image'),
                  # unblur tagbox
                  path('show_tag/<pk>', views.show_tag, name='show_tag'),
                  # create new album
                  path('<str:archive_name>/<int:archive_id>/new_album/', views.AlbumCreateView.as_view(),
                       name='create_album'),
                  # album list
                  path('album_list/<int:archive_pk>', views.AlbumListView.as_view(), name='album_list'),
                  # album
                  path('album/<pk>', views.AlbumView.as_view(), name='album'),
                  # delete album
                  path('album/<pk>/delete', views.delete_album, name='delete_album'),
                  # update album
                  path('album/<pk>/update', views.AlbumUpdateView.as_view(), name='update_album'),

                  # get autocomplete suggestions from database
                  path('autocomplete/', views.autocomplete, name='autocomplete'),
                  # sets the language of the app
                  path('set_language', views.set_language, name='set_language'),
                  # feedback form
                  path('feedback/', views.feedback_view, name='feedback'),
                  # privacy settings
                  path('privacy_settings/', views.PrivacySettingsView.as_view(), name='privacy_settings'),
                  # hide personal data
                  path('hide_personal_data/', views.hide_personal_data, name='hide_personal_data'),
                  # delete account and all data
                  path('delete_account/<str:uidb64>/<str:token>', views.DeleteAccountView.as_view(),
                       name='delete_account'),

                  # dashboard for usage statistics
                  path('dashboard/', views.DashboardView.as_view(), name='dashboard'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

arch/arch_app/models.py
import os

from django.conf import global_settings
from django.conf import settings
import uuid
import datetime

from django.core.exceptions import ObjectDoesNotExist
# from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from guardian.shortcuts import assign_perm, remove_perm
from django.db.models.signals import post_save, post_delete, pre_save, pre_delete
from django.dispatch import receiver
from django.utils.translation import gettext as _
from .file_validators import FileValidator
from .manager import TrackerManager, RecordManager


# from django.core.mail import send_mail

#######################
###  Basic Models  ###

class Location(models.Model):
    """ Basic Location model """
    name = models.CharField(max_length=120, null=True, blank=True)
    country = models.CharField(max_length=120, null=True, blank=True)
    country_code = models.CharField(max_length=2, null=True, blank=True)
    state = models.CharField(max_length=120, null=True, blank=True)
    region = models.CharField(max_length=120, null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Locations"

    def __str__(self):
        return f"{self.name} ({self.country_code})"


#######################
###  User & Groups  ###


def upload_archive_picture_get_path(instance, filename):
    """ returns the relative path where to upload house profile picture """
    return os.path.join(f"archive_{str(instance.id)}",
                        'archive_info',
                        f"profile_picture_{str(instance.id)}.jpg"
                        )


class Archive(models.Model):
    """ an archive is a collection of albums """
    name = models.CharField(max_length=128, unique=True)
    # this group is used for permission control
    moderators = models.OneToOneField(Group, on_delete=models.SET_NULL, null=True, blank=True)
    inbox = models.OneToOneField("Album", on_delete=models.SET_NULL, null=True, blank=True,
                                 related_name="archive_of_inbox")
    location = models.OneToOneField(Location, on_delete=models.SET_NULL, null=True, blank=True)
    institution_name = models.CharField(max_length=128)
    profile_picture = models.ImageField(upload_to=upload_archive_picture_get_path, null=True, default=None, blank=True)
    description = models.TextField(max_length=2500, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Archives"
        permissions = (
            ("is_moderator", "Has moderator permissions."),
        )

    def get_members(self):
        return self.members.distinct()

    def get_active_members(self):
        memberships = Membership.objects.filter(archive=self)
        memberships = [membership for membership in memberships if membership.is_active]
        active_members = User.objects.filter(
            membership__in=memberships
        )
        return active_members.distinct()

    def get_active_moderators(self):
        # memberships = Membership.objects.filter(archive=self, role="staff")
        # memberships = [membership for membership in memberships if membership.is_active]
        # active_staff_members = User.objects.filter(
        #     membership__in=memberships
        # )
        # return active_staff_members.distinct()
        return self.moderators.user_set.all()

    def __str__(self):
        return self.name


@receiver(post_save, sender=Archive)
def create_inbox_and_moderator_group(sender, instance, created, **kwargs):
    """ Automatically create an inbox and moderator group if an archive is created """
    if created:
        instance.inbox = Album.objects.create(
            title=f"{instance.name} Inbox",
            archive=instance,
            is_inbox=True
        )
        instance.moderators = Group.objects.create(name=instance.name + " Moderators")
        # add permissions
        assign_perm('is_moderator', instance.moderators, instance)
        instance.save()


@receiver(pre_delete, sender=Archive)
def delete_inbox_and_moderator_group(sender, instance, **kwargs):
    """ Automatically delete an inbox and moderator group if an archive is deleted """
    if instance.inbox:
        instance.inbox.delete()
    if instance.moderators:
        instance.moderators.delete()


def upload_profile_picture_get_path(instance, filename):
    """ returns the relative path where to upload profile picture """
    return os.path.join('user_info', f"profile_picture_{str(instance.id)}.jpg")


class User(AbstractUser):
    """ a custom User class extending the Django User """
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    archives = models.ManyToManyField(Archive, through='Membership', related_name='members')
    bio = models.TextField(max_length=500, null=True, blank=True)
    #language = models.CharField(max_length=20, choices=global_settings.LANGUAGES, null=True, blank=True)
    country = models.CharField(max_length=30, null=True, blank=True)
    location = models.OneToOneField(Location, on_delete=models.SET_NULL, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    # FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # i.e. 2.5 MB
    image_validator = FileValidator(max_size=settings.MAX_FILE_SIZE,
                                    content_types="image",
                                    supported_formats=['png', 'jpeg']
                                    )
    profile_picture = models.ImageField(upload_to=upload_profile_picture_get_path,
                                        validators=[image_validator],
                                        null=True, default=None, blank=True)
    consent = models.BooleanField(null=False, default=False)
    visible = models.BooleanField(null=False, default=True)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

    def __str__(self):
        name_parts = [part for part in [self.first_name, self.last_name] if part]
        full_name = ' '.join(name_parts)
        return f"{self.username} ({full_name})" if full_name else self.username


@receiver(models.signals.post_delete, sender=User)
def auto_delete_profile_picture_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem when corresponding User object is deleted.
    """
    if instance.profile_picture:
        # check if the old file was not the default file
        if not instance.profile_picture.name == '/arch_app/icons/person-circle.svg':
            if os.path.isfile(instance.profile_picture.path):
                os.remove(instance.profile_picture.path)
    else:
        return False


@receiver(models.signals.pre_save, sender=User)
def auto_delete_profile_picture_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem when User object is updated with new profile picture file.
    """
    if not instance.pk:
        return False
    try:
        old_file = User.objects.get(pk=instance.pk).profile_picture
    except Record.DoesNotExist:
        # if the old file does not exist, no need to delete it
        return True

    if old_file:
        new_file = instance.profile_picture
        # check if the file was actually changed
        if not old_file == new_file:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)


class Membership(models.Model):
    """ a Membership relation between a User and an Archive"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    archive = models.ForeignKey(Archive, on_delete=models.CASCADE, null=True, related_name='memberships')
    ROLES = (
        ('moderator', _('moderator')),
        ('member', _('member'))
    )
    role = models.CharField(max_length=19, choices=ROLES, default="member")
    start_date = models.DateField(_('begin'), default=datetime.date.today)
    end_date = models.DateField(_('end'), null=True, blank=True)
    consent = models.BooleanField(default=False, null=False)

    @property
    def is_active(self):
        """" checks if a membership is active """
        if self.end_date and self.end_date < datetime.date.today():
            return False
        return True

    def is_moderator(self):
        """ checks if a membership is a moderator """
        if self.role == 'moderator':
            return True
        return False

    def __str__(self):
        if self.is_active:
            return f"{self.user.username} is member of {self.archive.name} " \
                   f"since {self.start_date}"
        return f"{self.user.username} was member of {self.archive.name} " \
               f"from {self.start_date} until {self.end_date}."


@receiver(post_save, sender=Membership)
def new_membership(sender, instance, created, **kwargs):
    """ Handles adding a new member to an archive
    - add the user to the archive inbox group
    - give user permissions to view the archive
    - if role is moderator, add to the archive moderators group
    """
    if created:
        instance.archive.inbox.group.user_set.add(instance.user)
        # set permissions using django guardian
        assign_perm('view_archive', instance.user, instance.archive)
        if instance.role == 'moderator' and instance.is_active:
            instance.archive.moderators.user_set.add(instance.user)


@receiver(post_save, sender=Membership)

arch/arch_app/templates/arch_app/account_settings.html
{#Adapted from https://www.bootdey.com/snippets/view/account-settings#}

{% extends "arch_app/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
    {{ user.username }}
{% endblock %}

{% block navbar %}
    {% include "arch_app/partials/navbar.html" %}
{% endblock %}


{% block content %}

    {% include "./partials/spinner.html" %}

    <div class="container-fluid flex-grow-1">

        <h4>{% trans "Account Settings" %}</h4>

        <div class="card overflow-hidden">

            <div class="row no-gutters ">
                <div class="col-md-3 pt-0">
                    <div class="list-group list-group-flush account-settings-links">
                        <a class="list-group-item list-group-item-action {% if request.resolver_match.url_name == 'profile' %} active {% endif %}" data-toggle="list"
                           href="{% url 'arch_app:profile' %}">{%  trans "Profile" %}</a>
                        <a class="list-group-item list-group-item-action {% if request.resolver_match.url_name == 'change_password' %} active {% endif %}" data-toggle="list"
                           href="{% url 'arch_app:change_password' %}">{% trans "Change Password" %}</a>
                        <a class="list-group-item list-group-item-action {% if request.resolver_match.url_name == 'privacy_settings' %} active {% endif %}" data-toggle="list"
                           href="{% url 'arch_app:privacy_settings' %}">{% trans "Privacy" %}</a>
                    </div>
                </div>


                <div class="col-md-7 mx-auto">

                    <div class="tab-content">

                        {% block account_settings %}

                        {% endblock %}

                    </div>

                </div>


            </div>


        </div>


    </div>


{% endblock %}

arch/arch_app/templates/arch_app/archive.html
{% extends "arch_app/base.html" %}
{% load i18n %}
{% load static %}
{% load guardian_tags %}
{% load arch_tags %}


{% block navbar %}
    {% include "./partials/navbar.html" %}
{% endblock %}

{% block title %}{{ archive.name }}
{% endblock %}

{% block content %}

{% include "./partials/spinner.html" %}


<h5>{{ archive.name }}</h5>
<div class="card">
    <div class="row no-gutters ">

        <div class="col-md-3 col-sm-12 pt-0">
            <div class="card-header border" style="height: 100%;">
            
                <ul class="nav nav-pills card-pills flex-md-column ">
                
                    <li class="nav-item account-settings-links">
                        <a class="nav-link list-group-item-action 
                            {% if request.resolver_match.url_name == 'archive' %}active 
                            {% else %} text-primary{% endif %}"
                           data-toggle="list"
                           href="{% url 'arch_app:archive' archive.name archive.pk %}">
                            {% trans "Home" %}
                        </a>
                    </li>
                
                    <li class="nav-item">
                        <a class="nav-link list-group-item-action {% if request.resolver_match.url_name == 'members' %} active {% else %} text-primary {% endif %}"
                           data-toggle="list"
                           href="{% url 'arch_app:members' archive.name archive.id %}">
                            {% trans "Members" %}
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link list-group-item-action  {% if request.resolver_match.url_name == 'album_list' %} active {% else %} text-primary {% endif %}"
                           data-toggle="list"
                           href="{% url 'arch_app:album_list' archive.pk %}">
                            {% trans "Albums" %}
                        </a>
                    </li>
                
                    <li class="nav-item">
                       <a class="nav-link list-group-item-action  text-primary"
                           href="{% url 'arch_app:album' archive.inbox.id %}">
                             <i class="bi bi-mailbox pr-2"></i>{% trans "Inbox" %}
                        </a>
                    </li>
                
                </ul>

            </div>
        </div>

        <div class="col-md-7 col-sm-12 mx-auto">
            <div class="card-body">
                <div class=" custom-card-archive tab-content my-sm-4 py-sm-3">
                    {% block archive_settings %}
                    {% endblock %}
                </div>
            </div>
        </div>
    
    </div>
</div>

{% endblock %}

{% block js %}
{#    <script src="{% static 'arch_app/js/preserve_toggle_state.js' %}"></script>#}
{% endblock %}

arch/arch_app/templates/arch_app/delete_account.html
{% extends "./base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load arch_tags %}

{% block navbar %}
    {% include "./partials/navbar.html" %}
{% endblock %}

{% block content %}

    <div class="row justify-content-center">

        <div class="col-8 justify-content-center">
            {% if account %}

                <h1>{% trans "Delete Account" %} {{ account.username }}</h1>
                <div>{% trans "Do you really want to delete the account?" %}</div>
                <div>{% trans "This action cannot be undone and all related data will be permanently removed." %}</div>
                <br>
                <form method="post" action="{% url 'arch_app:delete_account' uidb64 token %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-warning">{% trans "Yes, delete the account" %}</button>
                </form>

            {% else %}
                <div>{% trans "No account found to be deleted." %}</div>
            {% endif %}
        </div>

    </div>


{% endblock %}

arch/arch_app/templates/arch_app/record.html
{% extends "./base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% load arch_tags %}
{% load guardian_tags %}


{% block title %}
    {{ record.title }}
{% endblock %}

{% block navbar %}
    {% include "./partials/navbar.html" %}
{% endblock %}


{% block content %}
    {% include "./partials/spinner.html" %}
    <div class="container-fluid">

        <div class="row pt-4">
            <div class="col">
                <div class="d-flex justify-content-end">

                    {% if prev_record %}
                        <a class="nav-link" id="previous-record-file" title="Previous"
                           href="{% url 'arch_app:record' prev_record.pk %}"
                           onclick="window.arch.addQueryParamsToLink(this.id)">
                            <i class="bi bi-arrow-left fs-3 text-primary"></i>
                        </a>
                    {% else %}
                        <a class="nav-link color-link-record-view" id="" title="no previous entry"
                           href="#">
                            <i class="bi bi-arrow-left fs-3 text-secondary"></i>
                        </a>
                    {% endif %}

                    {% get_obj_perms user for record.album.archive as "archive_perms" %}
                    {% get_obj_perms user for record as "record_perms" %}
                    {% if "is_moderator" in archive_perms or "delete_record" in record_perms %}
                        {# tool bar which expands on click #}
                        <div class="rounded record-toolbar collapse" id="record-toolbar">

                            <div class="d-flex">
                                <a class="nav-link" title="{% trans "Delete" %}"
                                   href="{% url 'arch_app:delete_record' record.pk %}?album_mode={{ album_mode }}">
                                    <i class="bi bi-trash fs-3 text-danger"></i>
                                </a>

                                {#                            <a class="nav-link" title="{% trans "Download" %}"#}
                                {#                               href="{{ record.media_file.url }}">#}
                                {#                                <i class="bi bi-cloud-arrow-down fs-3"></i>#}
                                {#                            </a>#}
                                {#                            <div class="dropdown">#}
                                {#                                <a class="toggle btn" title="{% trans "Tag Person" %}"#}
                                {#                                   href="#" id="CreateTagDropdown" role="button"#}
                                {#                                   data-bs-toggle="dropdown" aria-expanded="false">#}
                                {#                                    <i class="bi bi-person-plus"></i>#}
                                {#                                </a>#}
                                {#                                <div class="dropdown-menu dropdown-menu-right"#}
                                {#                                     id="tag-dropdown-menu-{{ tagbox.id }}"#}
                                {#                                     aria-labelledby="CreateTagDropdown"#}
                                {#                                     style="width: fit-content; border: solid 1px lightgray;">#}
                                {#                                    <div class="container p-1">#}
                                {#                                        {% get_tag_form users=archive.get_active_members.all as tag_form %}#}
                                {#                                        {% include "./forms/create_tag_form.html" %}#}
                                {#                                    </div>#}
                                {#                                </div>#}
                                {#                            </div> <!-- end dropdown -->#}
                            </div> <!-- end d-flex -->
                        </div> <!-- end record-toolbar -->
                        <button class="btn" type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#record-toolbar" aria-expanded="false"
                                aria-controls="record-toolbar">
                            <i class="bi bi-three-dots-vertical"></i>
                        </button>
                    {% endif %}

                    <div class="toggle-detail-comment d-flex" data-album="{{ record.album.is_inbox }}">
                        <a id="btn-detail-record" class="nav-link text-secondary" href="#">
                            <i class="bi bi-info-circle-fill fs-3 "></i>
                        </a>
                        <a id="btn-detail-comments" class="nav-link" href="#">
                            <i class="bi bi-chat-left-text-fill fs-3"></i>
                        </a>
                    </div>

                    {% if next_record %}
                        <a class="nav-link" id="next-record-file" title="Next"
                           href="{% url 'arch_app:record' next_record.pk %}"
                           onclick="window.arch.addQueryParamsToLink(this.id)">
                            <i class="bi bi-arrow-right fs-3 text-primary"></i>
                        </a>
                    {% else %}
                        <a class="nav-link color-link-record-view text-secondary" title="no next record"
                           href="#">
                            <i class="bi bi-arrow-right fs-3"></i>
                        </a>
                    {% endif %}

                    <!-- Exit button with X icon -->
                    {#  check if user should return to search or album view  #}

                    <a class="nav-link" title="Close" id="close-record"
                            {% if album_mode == "True" %}
                       href="{% url 'arch_app:album' album.id %}?page={{ current_page }}"
                            {% else %}
                       href="{% url 'arch_app:search' %}?archive_id={{ archive.id }}&page={{ current_page }}"
                            {% endif %}
                       onclick="window.arch.addQueryParamsToLink(this.id)">
                        <i class="bi bi-x-lg fs-3 text-dark"></i>
                    </a>

                </div> <!-- end d-flex -->
            </div>  <!-- end col -->
        </div>  <!-- end row -->


        <div class="row">
            {#  contains record and description  #}

            {#  display record  #}
            <div class="col-md-8 mx-auto py-2 px-2 text-center">
                <div class="row">
                    <div class="col justify-content-center">
                        {% include "./partials/record/record_detail.html" %}
                    </div>
                </div>
            </div>  <!-- end col-md-8 -->

            {# record metadata  #}
            <div class="col-md-4 parent-record-metadata py-2">
                <div class="row">
                    <div class="col-md-12">
                        {#  Record details  #}
                        <div class="d-none" id="detail-record-container">
                            {% include "./forms/record_form.html" %}
                        </div>

                        {#  Comments  #}
                        <div class="d-none" id="detail-comments-container">
                            <div class="row">
                                <div class="col-12 scrollable-div" style="min-height: 0; max-height: 20rem;">
                                    {% for comment in record.comments.all %}
                                        <div class="row justify-content-center">
                                            <div class="col-12">
                                                {% include "./partials/comment.html" %}
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>

                            {#  New comment  #}
                            <div class="row comment-form justify-content-center">
                                <div class="col-12 pt-4">
                                    {% include "./forms/comment_form.html" %}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

{% block js %}
{#    <script src="{% static 'arch_app/js/record.js' %}"></script>#}
    <script>
        window.arch.initRecord();
    </script>
{#    <script src="{% static 'arch_app/js/remove_tag.js' %}"></script>#}
{#    <script src="{% static 'arch_app/js/utils.js' %}"></script>#}
{% endblock %}